bin/media_watch: media_watch.swift
	@mkdir -p $(HOME)/.config/sketchybar/helpers/event_providers/media_watch/bin
	swiftc -O $< -o $(HOME)/.config/sketchybar/helpers/event_providers/media_watch/bin/media_watch
