format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$character"""

right_format = """
$status\
$cmd_duration\
${custom.time}\
"""

add_newline = false

[directory]
read_only = " 󰌾"
style = "fg:blue"
read_only_style = "fg:bright-red"
truncation_length = 3
truncation_symbol = "…/"
format = "[ $path]($style)[$read_only]($read_only_style) "

[os]
disabled = false
format = "[$symbol ]($style)"
style = "fg:purple"

[custom.time]
when = true
command = """
#!/bin/zsh
HOUR=$(date +%H)
TIME=$(date "+%Y-%m-%d %H:%M")
if [ $HOUR -lt 6 ]; then
    ICON="⏾"  # 凌晨
elif [ $HOUR -lt 12 ]; then
    ICON="☼"   # 上午
elif [ $HOUR -lt 18 ]; then
    ICON="⛅︎"   # 下午
else
    ICON="☪︎"   # 晚上
fi
echo "$ICON $TIME"
"""
# shell = ["zsh", "-c"]
style = "fg:gray"
format = "[$output]($style)"

[status]
disabled = false
symbol = "[✘](bold red) $status"
success_symbol = "[✔︎](bold green)"
format = "$symbol "
map_symbol = false

[cmd_duration]
disabled = false
min_time = 2000
format = "[☕︎$duration]($style) "
style = "bold fg:yellow"

[aws]
disabled = true
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[cmake]
disabled = true
symbol = " "

[conda]
disabled = true
symbol = " "

[crystal]
disabled = true
symbol = " "

[dart]
symbol = " "

[docker_context]
disabled = true
symbol = " "

[elixir]
disabled = true
symbol = " "

[elm]
disabled = true
symbol = " "

[fennel]
disabled = true
symbol = " "

[fossil_branch]
disabled = true
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = "  "

[golang]
symbol = " "

[guix_shell]
disabled = true
symbol = " "

[haskell]
disabled = true
symbol = " "

[haxe]
disabled = true
symbol = " "

[hg_branch]
disabled = true
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
disabled = true
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
disabled = true
symbol = "󰍛 "

[meson]
disabled = true
symbol = "󰔷 "

[nim]
disabled = true
symbol = "󰆥 "

[nix_shell]
disabled = true
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[package]
disabled = true
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
disabled = true
symbol = " "

[python]
symbol = " "

[rlang]
disabled = true
symbol = "󰟔 "

[ruby]
disabled = true
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
disabled = true
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
