#!/bin/bash

# 窗口外框唯一参数源。SketchyBar 启动和切换主题时传入准确颜色；
# 手动执行则使用当前默认 scheme (Everforest) 的 dark green。
active_color="${BORDERS_ACTIVE_COLOR:-0xffa7c080}"

borders \
  style=round \
  width=5.0 \
  hidpi=on \
  order=above \
  active_color="$active_color" \
  inactive_color=0x00000000
