# 状态栏
StatusBar=Hidden
# 模拟按键释放
SimulateKeyRelease=False
# 模拟按键释放延迟毫秒数
SimulateKeyReleaseDelay=100
# 监视剪贴板
MonitorPasteboard=False
# 清除追踪参数
RemoveTrackingParameters=True
# 轮询剪贴板的间隔（秒）
PollPasteboardInterval=2

[AppDefaultIM]
0="{\"appPath\":\"\\/Applications\\/Ghostty.app\\/\",\"appId\":\"com.mitchellh.ghostty\",\"imName\":\"keyboard-us\"}"
1="{\"appPath\":\"\\/Applications\\/Raycast Beta.app\\/\",\"appId\":\"com.raycast-x.macos\",\"imName\":\"keyboard-us\"}"

[VimMode]
0=com.neovide.neovide

