[Basic]
# 跟随光标
FollowCaret=True
# 主题
Theme=System
# 默认主题
DefaultTheme=System

[LightMode]
# 覆盖默认值
OverrideDefault=True
# 高亮颜色
HighlightColor=#c6a0f6
# 悬停时高亮颜色
HighlightHoverColor=#e189e2
# 高亮文本颜色
HighlightTextColor=#ffffff
# 按下时高亮文本颜色
HighlightTextPressColor=#7f7f7f
# 高亮标签颜色
HighlightLabelColor=#ffffff
# 高亮注释颜色
HighlightCommentColor=#ffffff
# 高亮标记颜色
HighlightMarkColor=#ffffff
# 面板颜色
PanelColor=#fff3eb
# 文本颜色
TextColor=#ed8796
# 标签颜色
LabelColor=#ff7000
# 注释颜色
CommentColor=#7bc0df
# 翻页按钮颜色
PagingButtonColor=#eed49f
# 禁用的翻页按钮颜色
DisabledPagingButtonColor=#7f7f7f
# 指示文本颜色
AuxColor=#000000
# 光标前的预编辑颜色
PreeditColorPreCaret=#000000
# 预编辑光标颜色
PreeditColorCaret=#000000
# 光标后的预编辑颜色
PreeditColorPostCaret=#000000
# 边框颜色
BorderColor=#f3d2dc
# 分隔线颜色
DividerColor=#f5a97f

[DarkMode]
# 覆盖默认值
OverrideDefault=True
# 与浅色模式相同
SameWithLightMode=False
# 高亮颜色
HighlightColor=#c6a0f6
# 悬停时高亮颜色
HighlightHoverColor=#e189e2
# 高亮文本颜色
HighlightTextColor=#fff9f9
# 按下时高亮文本颜色
HighlightTextPressColor=#7f7f7f
# 高亮标签颜色
HighlightLabelColor=#fff9f9
# 高亮注释颜色
HighlightCommentColor=#fff9f9
# 高亮标记颜色
HighlightMarkColor=#ffffff
# 面板颜色
PanelColor=#29273c
# 文本颜色
TextColor=#ed8796
# 标签颜色
LabelColor=#ff7000
# 注释颜色
CommentColor=#7dc4e4
# 翻页按钮颜色
PagingButtonColor=#eed49f
# 禁用的翻页按钮颜色
DisabledPagingButtonColor=#7f7f7f
# 指示文本颜色
AuxColor=#ffffff
# 光标前的预编辑颜色
PreeditColorPreCaret=#ffffff
# 预编辑光标颜色
PreeditColorCaret=#ffffff
# 光标后的预编辑颜色
PreeditColorPostCaret=#ffffff
# 边框颜色
BorderColor=#e189e2
# 分隔线颜色
DividerColor=#f5a97f

[Typography]
# 布局
Layout=Horizontal
# 书写模式
WritingMode="Horizontal top-bottom"
# 输入法感知版式
TypographyAwarenessForIM=True
# 垂直时注释右对齐
VerticalCommentsAlignRight=False
# 翻页按钮样式
PagingButtonsStyle=Triangle

[ScrollMode]
# 启用卷轴
EnableScroll=True
# 自动展开
AutoExpand=False
# 显示滚动条
ShowScrollBar=True
# 动画
Animation=True
# 最大行数
MaxRowCount=6
# 最大列数
MaxColumnCount=6
# 选词
SelectCandidate=
# 用主键盘数字键选词
UseMainKeyboardNumberKeys=True
# 用小键盘数字键选词
UseKeypadNumberKeys=False
# 针对 Hyper 键优化
OptimizeForHyperKey=True

[ScrollMode/Expand]
0=equal
1=Down

[ScrollMode/Collapse]
0=minus

[ScrollMode/Up]
0=minus
1=Up

[ScrollMode/Down]
0=equal
1=Down

[ScrollMode/Left]
0=Left

[ScrollMode/Right]
0=Right

[ScrollMode/RowStart]
0=Home

[ScrollMode/RowEnd]
0=End

[ScrollMode/PageUp]
0=Page_Up

[ScrollMode/PageDown]
0=Next

[ScrollMode/Commit]
0=space

[Background]
# 图片
ImageUrl=
# 有图片时保留面板颜色
KeepPanelColorWhenHasImage=False
# 模糊
Blur=None
# 阴影
Shadow=True

[Font]
# 文本字号
TextFontSize=18
# 文本字重
TextFontWeight=400
# 标签字号
LabelFontSize=14
# 标签字重
LabelFontWeight=500
# 注释字号
CommentFontSize=14
# 注释字重
CommentFontWeight=500
# 预编辑字号
PreeditFontSize=16
# 预编辑字重
PreeditFontWeight=400

[Font/TextFontFamily]
0=system-ui

[Font/LabelFontFamily]
0=system-ui

[Font/CommentFontFamily]
0=system-ui

[Font/PreeditFontFamily]
0=system-ui

[Caret]
# 样式
Style=Blink
# 文本
Text=‸

[Highlight]
# 标记样式
MarkStyle=None
# 标记文本
MarkText=🐧
# 悬停行为
HoverBehavior=None

[Size]
# 覆盖默认值
OverrideDefault=True
# 边框宽度（px）
BorderWidth=1
# 边框半径（px）
BorderRadius=15
# 外边距（px）
Margin=0
# 高亮半径（px）
HighlightRadius=0
# 顶填充（px）
TopPadding=3
# 右填充（px）
RightPadding=7
# 底填充（px）
BottomPadding=3
# 左填充（px）
LeftPadding=7
# 标签、文本、注释间隔（px）
LabelTextGap=7
# 垂直时最小宽度（px）
VerticalMinWidth=200
# 卷轴单元格宽度 (px)
ScrollCellWidth=65
# 水平分隔线宽度（px）
HorizontalDividerWidth=1

[Advanced]
# 用户 CSS
UserCss=
# 复制 HTML
CopyHtml=
# 我知道使用插件可能有风险
PluginNotice=False
# 插件
Plugins=

[Advanced/UnsafeAPI]
# curl
EnableUnsafeCurlAPI=False

