#!/usr/bin/env lua

-- Load the sketchybar-package and prepare the helper binaries
package.loaded["helpers"] = nil
require("helpers")

local settings = require("settings")
settings.ensure_toggle(settings.height)

require("init")
